/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Queue;
import java.util.Stack;

import com.kevinolarte.ejr.trimestre3.t10.ejer02.ArrayListEstadisticas;
import com.kevinolarte.ejr.trimestre3.t10.ejer05.Ejer05;
import com.kevinolarte.ejr.trimestre3.t10.ejer06.Ejer06;
import com.kevinolarte.ejr.trimestre3.t10.ejer07.Ejer07;
import com.kevinolarte.ejr.trimestre3.t10.ejer08.Ejer08;
import com.kevinolarte.ejr.trimestre3.t10.ejer09.Ejer09;
import com.kevinolarte.ejr.trimestre3.t10.ejerSuelto.Ejer01;
import com.kevinolarte.lib.LibConf;
import com.kevinolarte.propuestas.HashMaps;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Ejer09 a = new Ejer09();
      
       


    }
}
