/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Queue;
import java.util.Stack;

import com.kevinolarte.ejr.trimestre3.t10.ejer11.Centro;
import com.kevinolarte.ejr.trimestre3.t10.ejer11.Ejer11;
import com.kevinolarte.ejr.trimestre3.t10.ejerSuelto.Ejer01;
import com.kevinolarte.lib.LibConf;
import com.kevinolarte.propuestas.HashMaps;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String codigo = " asd";
        String nombre = " asd";
        String dniProfesor = "";
        if (codigo.isEmpty() || nombre.isEmpty() || dniProfesor.isEmpty()){
            System.out.println("Bien");
        }
       
      
       


    }
}
