/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaclase.app;

import javaclase.con.kevinolarte.ejr.tema07_2.Pila;
import javaclase.con.kevinolarte.ejr.tema07_2.analizadorTexto;
import javaclase.con.kevinolarte.ejr.tema07_2.recoletorTexto;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        recoletorTexto ejr02 = new recoletorTexto();
        analizadorTexto ejr03 = new analizadorTexto(new Pila(5), ejr02.getTexto());
        System.out.println(ejr03.correctorCodigo());
    }
}
