package com.kevinolarte.ejr.trimestre3.t10.ejer11;

public enum Materias {
    MATEMTICAS, CASTELLANO, VALENCIANO, 
    BIOLOGIA, HISTORIA, GEOGRAFIA, 
    INGLES, FRANCES, FISICA, 
    QUIMICA, TECNOLOGIA, EDUCACION_FISICA, 
    RELIGION, ETICA, MUSICA, PLASTICA, 
    INFORMATICA, ECONOMIA, EMPRESA, 
    DERECHO, FILOSOFIA, PSICOLOGIA, 
    SOCIOLOGIA, FORMACION_PROFESIONAL, 
    ORIENTACION, TUTORIA;
}
