package com.kevinolarte.ejr.trimestre3.t10.ejer11;

public enum Salida {
    CORRECTO, PARAMETROS_NO_VALIDO, PARAMETROS_DUPLICADOS, 
    GRUPO_EXISTENTE, ASIGNATURA_EXISTENTE, ALUMNO_EXISTENTE,
    PROFESOR_EXISTENTE, AULA_EXISTENTE; 
}
