package com.kevinolarte.ejr.trimestre3.t10.ejer11;

public enum Salida {
    CORRECTO, PARAMETROS_NO_VALIDO, PARAMETROS_DUPLICADOS, 
    GRUPO_EXISTENTE, ASIGNATURA_EXISTENTE, ALUMNO_EXISTENTE,
    PROFESOR_EXISTENTE, ASIGNATURA_NO_EXISTENTE, AULA_EXISTENTE,
    PROFESOR_NO_EXISTENTE, GRUPO_NO_EXISTENTE, ALUMNO_NO_EXISTENTE,
    AULA_NO_EXISTENTE;
}
